config/routes.rb
Rails.application.routes.draw do
 root :to =>'home#index'
 resources :users
 resources :venue
 resources :photos

 post '/search' => 'home#search'
 
 get '/login' =>	'session#new'
 post '/login' => 'session#create'
 delete '/login' => 'session#destroy'

  # root 'home#index'
  # post '/search' => 'home#search'

end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id          :integer          not null, primary key
#  image       :string(255)
#  user_id     :string(255)
#  venue_photo :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Photo < ActiveRecord::Base
  belongs_to :user #, dependent: :destroy
  belongs_to :venue
  mount_uploader :image, ImageUploader
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  avatar          :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :photos, :dependent => :destroy 
  has_many :venues
  validates :avatar, :presence => true
  validates :username, :presence => true, :length => { :minimum => 3 }
  mount_uploader :avatar, AvatarUploader
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id         :integer          not null, primary key
#  venuename  :string(255)
#  avatar     :string(255)
#  user_id    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Venue < ActiveRecord::Base
  has_many :photos
  belongs_to :user
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user

  private

  def authenticate_user
    if session[:user_id].present?
      @current_user = User.where(:id => session[:user_id]).first
      # finding a user
    end

    if @current_user.nil?
      session[:user_id] = nil
    end
  end

end

app/controllers/home_controller.rb
# class HomeController < ApplicationController
# 	def index
# 	end
# 	def search
# 		parameters = { term: pramas[:term], limit: 4}
# 		render json: Yelp.client.search('Sydney', parameters )
# 	end
# end

class HomeController < ApplicationController
  def index
  end

  def search
  	# Search term (e.g. "food", "restaurants"). If term isn't included we search everything.
    parameters = { term: params[:term]} #,limit: 20 
    render json: Yelp.client.search('Sydney', parameters)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
		@photos = Photo.all
	end

	def create
    photo = Photo.new photo_params
    photo.user = @current_user
    photo.save
    redirect_to photo
   end

  def new
    @user = @current_user
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find params[:id]
  end

  def show
    @photo = Photo.find params[:id]
  end
  
  def update
    photo = Photo.find params[:id] 
    photo.update photo_params
    redirect_to photo
  end
  
  def destroy
    photo = Photo.find params[:id] 
    photo.destroy
    redirect_to photos_path
  
  end



  private
  def photo_params
    params.require(:photo).permit(:image, :venue_photo, :image_cache, :user_id)
  end
end
		
	

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # binding.pry // :id => userdetails
    user = User.find_by(:username => params[:username])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:notice] = "Invalid login - please try again."
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id #Auto login
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def show
    
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params

    flash[:notice] = "User details is now updated."

    redirect_to user
  end
  def destroy
    user = User.find params[:id]
    user.destroy

    flash[:notice] = "User account is now deleted."
    redirect_to root_path
  end

private
  def user_params
    params.require(:user).permit(:username, :avatar, :avatar_cache, :password, :password_confirmation)
  end

  # def check_if_logged_in
  #   redirect_to(new_user_path) if @current_user.nil?
  # end

  # def check_if_admin
  #   redirect_to(root_path) if @current_user.is_admin?
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
#map_canvas

#control_container
  #map_search
    form
      input type='text'
      a#map_search_submit href='#': span.glyphicon.glyphicon-search
     
	/ # = render :partial => "/shared/nav_login"
  .attribution
    p powered by Yelp
    p.burst= image_tag 'burst_tiny.png'

  #results

#login_container
	form
		#login_submit
	 		/ = submit_tag 'Login'
    = render :partial => "/shared/nav_login"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xplore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS']}&sensor=true" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" %>
   <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" %>
</head>
<body>
	 
<%= yield %>



</body>
</html>

app/views/photos/_form.html.erb
 <div class="container">

        <div class="row">
            <div class="box">
               <div class="col-lg-12 text-center">
                  <div class="img-responsive img-border img-full">


        <div class="row">
            <div class="box">


                   <%= form_for @photo, :url => { :action => "create" } do |f| %>
                      <p class="nav nav-pills ">Xplore Name: <%= @current_user.username  %> </p>
                      <br>
                      <p >
                      <p class="nav nav-pills ">Venue: <%= f.text_field :venue_photo %></p>
                      <%= f.label :UploadPhoto %>
                      <%= f.file_field :image, :class => 'btn btn-primary' %>
                      <%= f.hidden_field :image_cache, :class => 'thumb' %>
                      </p>
                      <br>

                      <%= f.submit :class =>"btn btn-primary" %>

                      <hr>
                <% end %>
              </div>
            </div>
          </div>

                    
                      	
                      	

app/views/photos/edit.html.erb
<div class ="navbar navbar-fixed-top">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">

					<h1>update to a better PHoto!
	         </h1>


					
				</div>
	  	</div>
	  </div>
	</div>


<%= render :partial => 'form' %>

app/views/photos/index.html.erb
<div class ="navbar navbar-fixed-top">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">
          <h1> Xplore Photo Feed </h1>
        </div>
    </div>
  </div>
</div>

<div class="container">

        <div class="row">
            <div class="box">
               <div class="col-lg-12 text-center">
                  <div class="img-responsive img-border img-full">
                    <% @photos.reverse.each do |photo| %>
                      <div class='font2'>
                        <% if photo.user.present? %>
                        <%= link_to(photo.user.username, photo_path(photo)) %> </li>
                        <% else %>
                        <%= photo.user %>
                        <% end %>  
                    </div> 
                    <h3>Venue: <%= link_to(photo.venue_photo,photo_path(photo)) %></h3>
                   <div class='thumb2'>
                 <p><%= image_tag(photo.user.avatar_url, :class => 'thumb') if photo.user %></p>
              </div>
             <br>
            <p><%= image_tag(photo.image_url, :class => 'xthumb') if photo.user %></p>
                <% if photo.user == @current_user %>
                <%= link_to'Delete', photo , :data => {:method => :delete, :confirm => 'Really delete the Whole Post?' } %>
                <% end %>
            <hr>
  
        <footer>
          <div class ="navbar navbar-fixed-bottom">
            <div class ="navbar-inner">
              <div class ="container">
                <div class = "nav1" >   
                    <%= link_to(' Add  A New Photo |', new_photo_path) %>
                    <%= link_to'Delete photo |', @photo, :data => {:method => :delete, :confirm => 'Really delete this PHOto?' } %>
                    <p><%= link_to('Back to search', root_path) %></p>
                </div>      
              </div>
            </div>   
          </div>
        </footer>    
      <% end %>

app/views/photos/new.html.erb
<div class ="navbar navbar-fixed-top">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">
		      <h2>Add a PHoto! <%= image_tag(@photo.user.avatar_url, :class => 'thumb') if @photo.user %></h2>
	     	</div>
	  	</div>
	  </div>
	</div>
	
		<%= render :partial => 'form' %>
		
	

app/views/photos/show.html.erb
	<div class ="navbar navbar-fixed-top">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">
					
					<h1 >Hello! <%= link_to(@photo.user.username, @photo.user) if @photo.user %>
						<%= image_tag(@photo.user.avatar_url, :class => 'userlogin') if @photo.user %>
					<h1>
				</div>
	    </div>
	  </div>
	</div>

		
		<div class="container">

        <div class="row">
            <div class="box">
               <div class="col-lg-12 text-center">
                  <div class="img-responsive img-border img-full">
											<h3>Venue: <%= link_to(@photo.venue_photo, @photo.user) %></h3>
											<%= image_tag(@photo.image_url, :class => 'xthumb') if @photo.user %>
										
										<hr>
                  
                 
                </div>
             </div>
          </div>
      </div>
							        
<footer>
   <div class ="navbar navbar-fixed-bottom">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav1"	>		


							<% if @photo.user == @current_user %>

									<%= link_to'Edit PHoto! |', edit_photo_path %>
									<%= link_to(' Add  A New Photo |', new_photo_path) %>
									<%= link_to'Delete photo |', @photo, :data => {:method => :delete, :confirm => 'Really delete this PHOto?' } %>

									
							<% end %>

									<%= link_to " check out Xplore feed", photos_path %> 
									<p><%= link_to('Back to search', root_path) %></p>
						</div>      
        </div>
      </div>   
    </div>
  </footer>

	 

  

app/views/shared/_nav_login.haml
- if @current_user 
	%p= image_tag @current_user.avatar, :class => 'userlogin'
	%p= link_to " Hi #{@current_user.username.upcase}", user_path(@current_user)
	= link_to 'Upload Photo |', new_photo_path(@current_user) 
	= link_to 'Xplore Feed |', photos_path 
	= link_to 'Log Out', '/login', :data => {:method => :delete, :confirm => 'Really logout?' }
- else
	%h4 LOG IN
	= form_tag '/login' do
		%p
		= label_tag 'username'
		= text_field_tag 'username', nil ,:autofucus =>true
		%p
		= label_tag 'password'
		= password_field_tag 'password'
		%p
		= submit_tag 'Login', :id =>'userdetails'
		= link_to 'Sign Up', new_user_path

app/views/users/_form.html.erb
      
<div class="container">

        <div class="row">
            <div class="box">
               <div class="col-lg-12 text-center">
                  <div class="img-responsive img-border img-full">


        <div class="row">
            <div class="box">
               

              <%= form_for @user do |f| %>
                  <p class="nav nav-pills ">
                  <%= f.label :username %>
                  <%= f.text_field :username, :autofocus => true, :class => "form-control" %>
                  </p>
                  <p>
                  <%= f.label :avatar %>
                  <%= f.file_field :avatar , :class => 'btn btn-primary'%>
                  <%= f.hidden_field :avatar_cache, :class => "css_avatar" %>
                  </p>

                  <p class="nav nav-pills">
                  <%= f.label :password %>
                  <%= f.password_field :password, :class => "form-control" %>
                  </p>
                  <br>
                  <p class="nav nav-pills nav-stacked">
                  <%= f.label :password_confirmation %>
                  <%= f.password_field :password_confirmation, :class => "form-control" %>
                  </p>
                  <br>

                  <%= f.button 'Update!',:class =>"btn btn-primary" %>
                  <hr>
                <% end %>
              </div>
            </div>
          </div>

app/views/users/edit.html.erb
<div class ="navbar navbar-fixed-top">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">
      <h3>Update Xplore  | <%= @user.username %>
      <%= image_tag(@user.avatar, :class => 'userlogin') %> 
    </h3>
		</div>
   </div>
  </div>
</div>


<%= render :partial => 'form' %>


 <footer>
   <div class ="navbar navbar-fixed-bottom">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">
			   <%= link_to "Xplore feed | ", photos_path %>
			  
			   
			      <% if @current_user == @user %>
			         <%= link_to'Delete Profile |', @user, :data => {:method => :delete, :confirm => 'Really delete the Whole Profile?' } %>
			         <%= link_to('Check out other Xplorer Profile ',users_path) %>
			         <p><%= link_to('Back to search', root_path) %></p>
			    <% else %>

			   <%= link_to('Back to search', root_path) %>
			  
			    <% end %> 
        </div>      
      </div>
    </div>   
  </div>
</footer>

app/views/users/index.html.erb
<div class ="navbar navbar-fixed-top">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">
          <h1>Xplorer's
          </h1>
         </div>
    </div>
  </div>
</div>


<div class="container">

        <div class="row">
            <div class="box">
               <div class="col-lg-12 text-center">
                  <div class="img-responsive img-border img-full">
                    <% @users.each do |user| %>
                      <div class="font">
                        <%= link_to(user.username, user) %>
                      </div>
                  <p> <%= image_tag(user.avatar, :class => 'xthumb') %></p>
                <hr>
  
            <footer>
             <div class ="navbar navbar-fixed-bottom">
              <div class ="navbar-inner">
                <div class ="container">
                  <div class = "nav1">
             
                    
                        <%= link_to('Add a New PHoto! |', new_photo_path) %>
                        <%= link_to('Edit your Profile |', edit_user_path(user)) %> 
                        <%= link_to('Delete your Profile |', user, :data => {:method => :delete, :confirm => 'Are You Sure to Delete the Whole Profile' }) %> 
                        <p><%= link_to('Back to search', root_path) %></p>
                   
                
                    </div>      
                  </div>
                </div>   
              </div>
            </footer>
          <% end %>
   	
    
   	


   

app/views/users/new.html.erb
<div class ="navbar navbar-fixed-top">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">

				<h2>Create User</h2>

				</div>
	  	</div>
	  </div>
	</div>



			
			<%= render :partial => 'form' %>
				
		

app/views/users/show.html.erb
<div class ="navbar navbar-fixed-top">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">
            
          <h1>Hello! <%= @user.username %>
          <%= image_tag(@user.avatar, :class => 'userlogin') %></h1>
        </div>
    </div>
  </div>
</div>

<div class="container">

        <div class="row">
            <div class="box">
               <div class="col-lg-12 text-center">
                  <div class="img-responsive img-border img-full">
                    
                      <% @user.photos.each do |photo| %>
                      <% if @user.photos.empty? %>
                          <h2> No PHoto, Add a new Photo of the venue you attended </h2>
                      <% else %>
                      
                       <p><%= link_to(image_tag(photo.image_url, :class => 'xthumb'), photo) %>
                       </p>
                       <% end %>

                       <hr>
                      
                  
                   <% end %>

                   <h2> No PHoto, Add a new Photo of the venue you attended </h2>
                </div>
             </div>
          </div>
      </div>




<footer>
  <div class ="navbar navbar-fixed-bottom">
    <div class ="navbar-inner">
      <div class ="container">
        <div class = "nav">
         <%= link_to "Xplore feed | ", photos_path %>
           
           <% if @current_user == @user %>
              <%= link_to'Delete Profile |', @user, :data => {:method => :delete, :confirm => 'Really delete the Whole Profile?' } %>
              <%= link_to'Edit Profile |', edit_user_path %>
              <%= link_to('Add a Photo |', new_photo_path) %>
              <%= link_to('Check out other Xplorer Profile ',users_path) %>
              <p><%= link_to('Back to search', root_path) %></p>

          <% else %>
            <%= link_to('Back to search', root_path) %>
          <% end %> 
        
        </div>      
      </div>
    </div>   
  </div>
</footer>
     
<!-- <hr> -->
  